name: Reviewpad

on:
  issues:
    types:
      - opened
  issue_comment:
    types:
      - created
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
      - converted_to_draft
      - edited
      - review_requested
      - review_request_removed
  pull_request_review:
  pull_request_review_comment:
  workflow_run:
    workflows: ["Pull Request Build"]
    types:
      - completed

jobs:
  reviewpad:
    if: ${{ github.event.actor != 'reviewpad-bot' }}
    runs-on: ubuntu-latest
    steps:
      - name: Reviewpad
        uses: reviewpad/action@v3.x
        with:
          token: ${{ secrets.REVIEWPAD_TOKEN }}
